@startuml

skinparam monochrome true
skinparam shadowing false

left to right direction

skinparam rectangle {
    BorderColor<<input>> Red
}

rectangle "" <<input>> {
    cloud X
}
rectangle SelectKBest
rectangle PCA
interface " " as c1
rectangle RandomForestRegressor
X --> SelectKBest
X --> PCA
SelectKBest --> c1
PCA --> c1
c1 --> RandomForestRegressor

@enduml
