@startuml

skinparam monochrome true
skinparam shadowing false

skinparam rectangle {
	borderColor lightGrey
}

rectangle "" <<Plotting>> {
    rectangle seaborn
    rectangle bokeh
    component matplotlib
}

rectangle "" <<Machine Learning>> {
    rectangle ibex
    component sklearn
}

rectangle "" <<Data Structures>> {
    rectangle pandas
    component numpy
}

[sklearn] -> [numpy] : interfaced by
[matplotlib] -> [numpy] : interfaced by
[pandas] ..> [numpy] : implemented over
[seaborn] -> [pandas] : interfaced by
[bokeh] -> [pandas] : interfaced by
[seaborn] ..-> [matplotlib] : implemented over
ibex -> [pandas] : interfaced by
ibex ..-> [sklearn] : implemented over

@enduml
