@startuml

skinparam monochrome true
skinparam shadowing false

actor user

autonumber 1 "<font color=grey>"
user -[#grey]> runtime: import ibex.sklearn.linear_model
runtime -[#grey]> ibex: import ibex
runtime -[#grey]> ibex.sklearn: import ibex.sklearn
ibex.sklearn -[#grey]> ibex.sklearn: register sys.metapath
runtime -[#grey]> loader: import ibex.sklearn.linear_model
autonumber 6 "<font color=black>"
loader -[#black]> sklearn.linear_model: **dir**
autonumber 7 "<font color=grey>"
sklearn.linear_model -[#grey]> loader: members
loader -[#grey]> loader: inspect
loader -[#grey]> loader: wrap

@enduml
