import glob
import os


PlantUMLBuilder = Builder(action = 'java -jar -Djava.awt.headless=true plantuml.jar -tpng $SOURCE -o generated/')
env = Environment(BUILDERS = {'PlantUMLBuilder' : PlantUMLBuilder})
for f_name in glob.glob('*.plantuml'):
    env.PlantUMLBuilder(os.path.splitext(f_name)[0] + '.png', f_name)
env.Program('index.html')
