import glob
import os


PlantUMLBuilder = Builder(action = 'java -jar -Djava.awt.headless=true plantuml.jar -tpng $SOURCE -o generated/')
env = Environment(BUILDERS = {'PlantUMLBuilder' : PlantUMLBuilder})

for f_name in glob.glob('*.plantuml'):
    src, target = f_name, os.path.join('generated', os.path.splitext(f_name)[0] + '.png')
    env.PlantUMLBuilder(target, src)
