@startuml

skinparam monochrome true
skinparam shadowing false

left to right direction

frame " " <<input>> {
    database X0
    database X1
    interface " " as c0
}
rectangle SelectKBest
rectangle PCA
interface " " as c1
rectangle RandomForestRegressor
X0 --> c0
X1 --> c0 
c0 --> SelectKBest
c0 --> PCA
SelectKBest --> c1
PCA --> c1
c1 --> RandomForestRegressor

@enduml
