@startuml

skinparam monochrome true
skinparam shadowing false

actor user

participant Wrapped

participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapped : predict(X)
autonumber 2 "<font color=black>"
Wrapped -[#black]> Wrapped : **validate; strip**
autonumber 3 "<font color=grey>"
Wrapped -[#grey]> Wrapped : predict(Xt)
wrapped -[#grey]> Wrapped : yt
Wrapped -[#grey]> Wrapped : add metadata
Wrapped -[#grey]> user : y

@enduml
