@startuml

skinparam monochrome true
skinparam shadowing false

actor user

participant Wrapper

participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapper : predict(X)
Wrapper -[#grey]> Wrapper : validate; strip
Wrapper -[#grey]> Wrapper : predict(Xt)
wrapped -[#grey]> Wrapper : yt
Wrapper -[#grey]> Wrapper : add metadata
autonumber 6 "<font color=black>"
Wrapper -[#black]> user : **y**

@enduml
