@startuml

skinparam monochrome true
skinparam shadowing false

actor user

participant Wrapped

participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapped : predict(X)
Wrapped -[#grey]> Wrapped : validate; strip
Wrapped -[#grey]> Wrapped : predict(Xt)
wrapped -[#grey]> Wrapped : yt
Wrapped -[#grey]> Wrapped : add metadata
autonumber 6 "<font color=black>"
Wrapped -[#black]> user : **y**

@enduml
