@startuml

skinparam monochrome true
skinparam shadowing false

actor user

participant Wrapper

participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapper : predict(X)
Wrapper -[#grey]> Wrapper : validate; strip
Wrapper -[#grey]> Wrapper : predict(Xt)
autonumber 4 "<font color=black>"
wrapped -[#black]> Wrapper : **yt**
autonumber 5 "<font color=grey>"
Wrapper -[#grey]> Wrapper : add metadata
Wrapper -[#grey]> user : y

@enduml
