@startuml

skinparam monochrome true
skinparam shadowing false

actor user
participant Wrapper
participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapper: <back:white>predict(X)</back>
autonumber 2 "<font color=grey>"
Wrapper -[#grey]> Wrapper: <back:white>validate; strip</back>
autonumber 3 "<font color=grey>"
Wrapper -[#grey]> wrapped: <back:white>predict(Xt)</back>
autonumber 4 "<font color=black>"
wrapped -[#black]> Wrapper: <back:grey>yt</back>
autonumber 5 "<font color=grey>"
Wrapper -[#grey]> Wrapper: <back:white>add metadata</back>
autonumber 6 "<font color=grey>"
Wrapper -[#grey]> user: <back:white>y</back>

@enduml