@startuml

skinparam monochrome true
skinparam shadowing false

actor user

participant Wrapper

participant wrapped

autonumber 1 "<font color=grey>"
user -[#grey]> Wrapper : predict(X)
autonumber 2 "<font color=black>"
Wrapper -[#black]> Wrapper : **validate; strip**
autonumber 3 "<font color=grey>"
Wrapper -[#grey]> Wrapper : predict(Xt)
wrapped -[#grey]> Wrapper : yt
Wrapper -[#grey]> Wrapper : add metadata
Wrapper -[#grey]> user : y

@enduml
