@startuml

skinparam monochrome true
skinparam shadowing false

actor user

autonumber 1 "<font color=grey>"
user -[#grey]> runtime: import ibex.sklearn.linear_model
runtime -[#grey]> ibex: import ibex
runtime -[#grey]> ibex.sklearn: import ibex.sklearn
ibex.sklearn -[#black]> ibex.sklearn: register sys.metapath
runtime -[#grey]> loader: import ibex.sklearn.linear_model
loader -[#grey]> sklearn.linear_model: dir
autonumber 7 "<font color=black>"
sklearn.linear_model -[#black]> loader: __members__
autonumber 8 "<font color=grey>"
loader -[#grey]> loader: inspect
loader -[#grey]> loader: wrap

@enduml
