@startuml

skinparam monochrome true
skinparam shadowing false

actor user
participant Wrapped
participant wrapped

autonumber 1 "<font color=black>"
user -[#black]> Wrapped: <back:grey>predict(X)</back>
autonumber 2 "<font color=grey>"
Wrapped -[#grey]> Wrapped: <back:white>validate; strip</back>
autonumber 3 "<font color=grey>"
Wrapped -[#grey]> Wrapped: <back:white>predict(Xt)</back>
autonumber 4 "<font color=grey>"
wrapped -[#grey]> Wrapped: <back:white>yt</back>
autonumber 5 "<font color=grey>"
Wrapped -[#grey]> Wrapped: <back:white>add metadata</back>
autonumber 6 "<font color=grey>"
Wrapped -[#grey]> user: <back:white>y</back>

@enduml